Make show_me! compatible with amazing_print + awesome_print
thbar/kiba-common pull request #32
Opened 2020-08-22 13:13 UTC by joshRpowell

@thbar closes #31

2020-08-22 13:19 UTC, joshRpowell commented on Changes.md
> +- Breaking: for Ruby 2.7+ `show_me!` requires `amazing_print` gem. `awesome_print` is no longer actively maintained.
went with 2.7+ here until [awesome_print updates its .travis.yml](https://github.com/awesome-print/awesome_print/blob/4564fd74721562cbef2443f7d97109bf9192343d/.travis.yml#L8) for 2.7 when "either or" would hold true.

2020-08-24 08:45 UTC, thbar requested changes
Thanks for the PR!

The tests are broken. Could you please require amazing print inside the "show me" test, so that the build comes back to green?

Thank you!

2020-08-24 08:45 UTC, thbar commented on Changes.md
> +- Breaking: for Ruby 2.7+ `show_me!` requires `amazing_print` gem. `awesome_print` is no longer actively maintained.
```suggestion
- Breaking: `show_me!` is now compatible with both `awesome_print` and its modern replacement `amazing_print`. You will have to `require` the one you want to use in your code from now on.
```

2020-08-24 08:46 UTC, thbar commented on README.md
> +A way to color-dump rows on the screen, useful during development when you are inspecting the data (requires the `amazing_print` gem).
```suggestion
A way to color-dump rows on the screen, useful during development when you are inspecting the data (requires either the `amazing_print` or the `awesome_print` gem).
```

2020-08-24 11:55 UTC, joshRpowell commented on README.md
> +A way to color-dump rows on the screen, useful during development when you are inspecting the data (requires either the `amazing_print` or the `awesome_print` gem).
👍

2020-08-24 11:55 UTC, joshRpowell commented on Changes.md
> +- Breaking: `show_me!` is now compatible with both `awesome_print` and its modern replacement `amazing_print`. You will have to `require` the one you want to use in your code from now on.
👍

2020-08-24 11:58 UTC, thbar commented
Thank you @joshRpowell! I will merge now.

2020-08-24 11:59 UTC, merged